#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Drive an OpenHands agent whose loop runs *inside* an OpenShell sandbox.

Architecture (B-server): the OpenHands `openhands-agent-server` runs inside a
policy-enforced OpenShell sandbox. This driver — running on the host — creates
the sandbox, launches the server bound to sandbox loopback, tunnels that port
out over an authenticated gateway gRPC forward, then connects to it with the
OpenHands SDK's remote-server client (`Workspace(host=...)` +
`RemoteConversation`). Because the agent loop executes server-side:

  * every tool action (bash, file edits) runs in the sandbox filesystem, and
  * the agent's OWN LLM calls egress through the sandbox's L7 policy proxy.

Point the LLM at `https://inference.local` and OpenShell injects the real
operator credentials outbound while the sandbox only ever holds a dummy key.
An unapproved `curl` from inside the sandbox is denied by the default-deny
network policy — the demo's "even a compromised agent cannot exfiltrate" beat.

Prerequisites (see README.md):
  * `bootstrap-kind.sh create` — kind cluster + gateway registered as `local`
  * `bootstrap-kind.sh forward` — port-forward held open in another terminal
  * an inference route configured so `inference.local` resolves (setup.sh)
"""

from __future__ import annotations

import argparse
import contextlib
import os
import shutil
import socket
import subprocess
import sys
import time
import uuid
from pathlib import Path

HERE = Path(__file__).resolve().parent

# The OpenShell Python SDK lives at <repo>/python/openshell as pure Python (its
# protobuf stubs are generated by `mise run python:proto`). We import it from
# source rather than as an installed package to avoid triggering a full Rust CLI
# recompile via the repo-root maturin build. See pyproject.toml for the rationale.
_SDK_DIR = HERE.parent.parent / "python"
if _SDK_DIR.is_dir() and str(_SDK_DIR) not in sys.path:
    sys.path.insert(0, str(_SDK_DIR))

from openshell import ExecResult, SandboxClient, SandboxError
from openshell._proto import openshell_pb2

DEFAULTS = {
    "cluster": os.environ.get("OPENSHELL_GATEWAY", "local"),
    "workspace": os.environ.get("OPENSHELL_WORKSPACE", "default"),
    "image": os.environ.get(
        "OPENHANDS_DEMO_IMAGE", "openshell-demo/openhands-sandbox:dev"
    ),
    "model": os.environ.get("OPENHANDS_MODEL", "anthropic/claude-sonnet-4-5"),
    # inference.local is the sandbox's magic host: the L7 proxy intercepts it,
    # routes to the configured provider, and injects the real key outbound.
    "llm_base_url": os.environ.get("OPENHANDS_LLM_BASE_URL", "https://inference.local"),
    # A dummy key satisfies litellm client-side; the sandbox strips it and the
    # gateway injects the real credential. Override only for a direct-to-API
    # bring-up test (then also set OPENHANDS_LLM_BASE_URL to the real endpoint).
    "llm_api_key": os.environ.get("OPENHANDS_LLM_API_KEY", "sk-openshell-injected"),
    "openshell_bin": os.environ.get("OPENSHELL_BIN", "openshell"),
    # Absolute path to the interpreter that has the OpenHands stack installed.
    # The demo image installs it into a dedicated venv (see Dockerfile); the base
    # sandbox image activates its OWN /sandbox/.venv ahead of ours on PATH, so a
    # bare `python3` would miss openhands — always launch via this explicit path.
    "server_python": os.environ.get(
        "OPENHANDS_SERVER_PYTHON", "/opt/openhands/bin/python3"
    ),
    "server_port": int(os.environ.get("OPENHANDS_SERVER_PORT", "8000")),
    # Directory INSIDE the sandbox the agent works out of. Must be writable
    # under the sandbox policy — the base image ships /sandbox and /tmp as
    # read-write; /sandbox is the natural home.
    "work_dir": os.environ.get("OPENHANDS_WORK_DIR", "/sandbox"),
    "policy": os.environ.get("OPENHANDS_POLICY", str(HERE / "policy.yaml")),
    "task": os.environ.get(
        "OPENHANDS_TASK",
        "Create a Python file hello.py that prints the first 10 Fibonacci "
        "numbers, then run it and report the output.",
    ),
    # A host that is NOT in the allowlist — used to prove default-deny egress.
    "blocked_host": os.environ.get("OPENHANDS_BLOCKED_HOST", "https://example.com"),
}


def log(msg: str) -> None:
    print(f"\033[1;36m[driver]\033[0m {msg}", flush=True)


def warn(msg: str) -> None:
    print(f"\033[1;33m[driver:warn]\033[0m {msg}", file=sys.stderr, flush=True)


def _exec(client: SandboxClient, sid: str, argv: list[str], **kw) -> ExecResult:
    """Run a command in the sandbox, returning the ExecResult."""
    return client.exec(sid, argv, **kw)


def apply_policy(cfg: dict, sandbox_name: str) -> None:
    """Apply the demo network policy via the CLI (reuses its YAML parser)."""
    policy_path = Path(cfg["policy"])
    if not policy_path.exists():
        warn(f"policy file {policy_path} not found; keeping the image default policy")
        return
    log(f"applying network policy from {policy_path.name}")
    subprocess.run(
        [
            cfg["openshell_bin"],
            "policy",
            "set",
            sandbox_name,
            "--policy",
            str(policy_path),
        ],
        check=True,
        env=_cli_env(cfg),
    )


def start_agent_server(cfg: dict, client: SandboxClient, sid: str) -> None:
    """Launch openhands-agent-server on sandbox loopback, detached."""
    port = cfg["server_port"]
    # nohup + background + disown so the server outlives this buffered exec and
    # is reparented to the supervisor (PID 1). Bound to loopback: the only way
    # in is the authenticated, loopback-only gateway tunnel.
    py = cfg["server_python"]
    workdir = cfg["work_dir"]
    # The server persists conversation state under a `workspace/` dir relative to
    # its CWD, so launch it from a policy-writable directory (the base image's
    # default CWD is not writable to the sandbox user).
    launch = (
        f"cd {workdir} && "
        f"nohup {py} -m openhands.agent_server "
        f"--host 127.0.0.1 --port {port} "
        f">/tmp/agent-server.log 2>&1 & disown; echo started"
    )
    log(f"starting openhands-agent-server on 127.0.0.1:{port}")
    result = _exec(
        client,
        sid,
        # `bash -c` (not `-lc`): a login shell can reset PATH via /etc/profile
        # and drop the OpenHands venv prepend baked into the image ENV, so avoid
        # it here where the venv's python3 must be found.
        ["bash", "-c", launch],
        # OH_SECRET_KEY encrypts any server-side stored secrets; random per run.
        env={"OH_SECRET_KEY": uuid.uuid4().hex},
        timeout_seconds=60,
    )
    if result.exit_code != 0:
        raise SandboxError(f"failed to launch agent-server: {result.stderr}")


def wait_server_ready(
    cfg: dict, client: SandboxClient, sid: str, timeout: float = 120.0
) -> None:
    """Poll the in-sandbox server until its port answers (any HTTP code)."""
    port = cfg["server_port"]
    deadline = time.time() + timeout
    # curl (without -f) exits 0 once it receives ANY HTTP response, and 7 while
    # the connection is refused — so exit 0 means "listening".
    probe = ["bash", "-lc", f"curl -s -o /dev/null http://127.0.0.1:{port}/"]
    while time.time() < deadline:
        result = _exec(client, sid, probe, timeout_seconds=15)
        if result.exit_code == 0:
            log("agent-server is accepting connections")
            return
        time.sleep(2)
    logs = _exec(client, sid, ["bash", "-lc", "cat /tmp/agent-server.log"]).stdout
    raise SandboxError(
        f"agent-server did not become ready within {timeout:.0f}s.\n"
        f"--- /tmp/agent-server.log ---\n{logs}"
    )


def start_tunnel(cfg: dict, sandbox_name: str) -> subprocess.Popen:
    """Forward a local port to the sandbox's loopback agent-server port."""
    port = cfg["server_port"]
    log(f"opening gateway tunnel localhost:{port} -> sandbox 127.0.0.1:{port}")
    proc = subprocess.Popen(
        [
            cfg["openshell_bin"],
            "forward",
            "service",
            sandbox_name,
            "--target-port",
            str(port),
            "--local",
            str(port),
        ],
        env=_cli_env(cfg),
        stdout=subprocess.DEVNULL,
        stderr=subprocess.STDOUT,
    )
    if not _wait_local_port(port, timeout=30.0):
        proc.terminate()
        raise SandboxError(f"tunnel local port {port} never came up")
    return proc


def run_agent(cfg: dict) -> None:
    """Connect the OpenHands remote client and run one task server-side."""
    # Imported lazily so `--help` and infra steps work without the OpenHands
    # SDK installed on the host.
    from openhands.sdk import LLM, Conversation, Workspace
    from openhands.tools.preset.default import get_default_agent
    from pydantic import SecretStr

    port = cfg["server_port"]
    base = f"http://127.0.0.1:{port}"

    llm = LLM(
        usage_id="agent",
        model=cfg["model"],
        base_url=cfg["llm_base_url"],
        api_key=SecretStr(cfg["llm_api_key"]),
    )
    # working_dir is a path INSIDE the sandbox (the server's filesystem).
    workspace = Workspace(host=base, working_dir=cfg["work_dir"])
    agent = get_default_agent(llm=llm, cli_mode=True)

    log("connecting remote conversation and dispatching the task")
    conversation = Conversation(agent=agent, workspace=workspace)
    try:
        conversation.send_message(cfg["task"])
        conversation.run()
        status = getattr(
            getattr(conversation, "state", None), "execution_status", "unknown"
        )
        events = getattr(getattr(conversation, "state", None), "events", []) or []
        log(f"conversation finished: status={status}, events={len(events)}")
    finally:
        close = getattr(conversation, "close", None)
        if callable(close):
            with contextlib.suppress(Exception):
                close()


def show_task_artifact(cfg: dict, client: SandboxClient, sid: str) -> None:
    """Print what the agent produced inside the sandbox."""
    wd = cfg["work_dir"]
    result = _exec(
        client,
        sid,
        ["bash", "-lc", f"ls -la {wd} && echo '---' && cat {wd}/hello.py"],
    )
    log("workspace contents after the run:")
    print(result.stdout, flush=True)


def demonstrate_egress(cfg: dict, client: SandboxClient, sid: str) -> None:
    """Money shot: an unapproved host is blocked by default-deny egress."""
    host = cfg["blocked_host"]
    log(f"attempting unapproved egress to {host} (expected: DENIED)")
    result = _exec(
        client,
        sid,
        ["bash", "-lc", f"curl -sS -m 15 -o /dev/null -w '%{{http_code}}' {host}"],
        timeout_seconds=30,
    )
    # The proxy answers CONNECT with 403; curl surfaces it as a non-zero exit
    # and/or a "403" from the proxy. Either way the fetch does not succeed.
    print(
        f"  exit_code={result.exit_code}\n"
        f"  stdout={result.stdout.strip()!r}\n"
        f"  stderr={result.stderr.strip()!r}",
        flush=True,
    )
    if result.exit_code == 0 and result.stdout.strip() not in {"", "403"}:
        warn(
            "egress to the unapproved host was NOT blocked — check that the "
            "sandbox policy is default-deny (policy.yaml)."
        )
    else:
        log("egress blocked as expected (default-deny network policy)")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cluster", default=DEFAULTS["cluster"])
    parser.add_argument("--workspace", default=DEFAULTS["workspace"])
    parser.add_argument("--image", default=DEFAULTS["image"])
    parser.add_argument("--model", default=DEFAULTS["model"])
    parser.add_argument("--task", default=DEFAULTS["task"])
    parser.add_argument(
        "--keep", action="store_true", help="do not delete the sandbox on exit"
    )
    parser.add_argument(
        "--no-policy", action="store_true", help="skip applying policy.yaml"
    )
    parser.add_argument(
        "--no-agent",
        action="store_true",
        help="stand up the server + tunnel but skip running the agent task",
    )
    args = parser.parse_args()

    cfg = dict(DEFAULTS)
    cfg.update(
        cluster=args.cluster,
        workspace=args.workspace,
        image=args.image,
        model=args.model,
        task=args.task,
    )

    if not shutil.which(cfg["openshell_bin"]):
        warn(
            f"'{cfg['openshell_bin']}' CLI not found on PATH — the tunnel and "
            f"policy steps need it. Set OPENSHELL_BIN or build openshell-cli."
        )

    name = f"openhands-{uuid.uuid4().hex[:8]}"
    tunnel: subprocess.Popen | None = None
    client = SandboxClient.from_active_cluster(cluster=cfg["cluster"])
    sandbox = None
    try:
        log(f"creating sandbox {name} from image {cfg['image']}")
        spec = openshell_pb2.SandboxSpec(
            template=openshell_pb2.SandboxTemplate(image=cfg["image"]),
        )
        sandbox = client.create(workspace=cfg["workspace"], spec=spec, name=name)
        log(f"waiting for sandbox {sandbox.name} to become ready")
        client.wait_ready(
            sandbox.name, workspace=cfg["workspace"], timeout_seconds=300.0
        )
        log("sandbox is ready")

        if not args.no_policy:
            apply_policy(cfg, sandbox.name)

        start_agent_server(cfg, client, sandbox.id)
        wait_server_ready(cfg, client, sandbox.id)
        tunnel = start_tunnel(cfg, sandbox.name)

        if not args.no_agent:
            run_agent(cfg)
            show_task_artifact(cfg, client, sandbox.id)

        demonstrate_egress(cfg, client, sandbox.id)
        return 0
    finally:
        if tunnel is not None:
            with contextlib.suppress(Exception):
                tunnel.terminate()
                tunnel.wait(timeout=10)
        if sandbox is not None and not args.keep:
            log(f"deleting sandbox {sandbox.name}")
            with contextlib.suppress(Exception):
                client.delete(sandbox.name, workspace=cfg["workspace"])
        elif sandbox is not None:
            log(f"leaving sandbox {sandbox.name} running (--keep)")
        client.close()


def _cli_env(cfg: dict) -> dict:
    env = dict(os.environ)
    # Point the CLI at the same gateway the SDK is using.
    env["OPENSHELL_GATEWAY"] = cfg["cluster"]
    return env


def _wait_local_port(port: int, *, timeout: float) -> bool:
    deadline = time.time() + timeout
    while time.time() < deadline:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
            sock.settimeout(1.0)
            if sock.connect_ex(("127.0.0.1", port)) == 0:
                return True
        time.sleep(0.5)
    return False


if __name__ == "__main__":
    raise SystemExit(main())
